export interface CityData {
    id: number;
    city: string;
    timezone: string;
}
export const timezoneData:CityData[] = [
    { id: 6, city: 'Kabul, Afghanistan', timezone: 'Asia/Kabul' },
    { id: 7, city: 'Tirana, Albania', timezone: 'Europe/Tirane' },
    { id: 8, city: 'Algiers, Algeria', timezone: 'Africa/Algiers' },
    { id: 9, city: 'Pago Pago, American Samoa', timezone: 'Pacific/Pago_Pago' },
    { id: 10, city: 'Andorra la Vella, Andorra', timezone: 'Europe/Andorra' },
    { id: 11, city: 'Luanda, Angola', timezone: 'Africa/Luanda' },
    { id: 12, city: 'The Valley, Anguilla', timezone: 'America/Anguilla' },
    { id: 13, city: 'Casey, Antarctica', timezone: 'Antarctica/Casey' },
    { id: 14, city: 'Davis, Antarctica', timezone: 'Antarctica/Davis' },
    { id: 15, city: 'Dumont d\'Urville, Antarctica', timezone: 'Antarctica/DumontDUrville' },
    { id: 16, city: 'Mawson, Antarctica', timezone: 'Antarctica/Mawson' },
    { id: 17, city: 'McMurdo, Antarctica', timezone: 'Antarctica/McMurdo' },
    { id: 18, city: 'Palmer, Antarctica', timezone: 'Antarctica/Palmer' },
    { id: 19, city: 'Rothera, Antarctica', timezone: 'Antarctica/Rothera' },
    { id: 20, city: 'Syowa, Antarctica', timezone: 'Antarctica/Syowa' },
    { id: 21, city: 'Troll, Antarctica', timezone: 'Antarctica/Troll' },
    { id: 22, city: 'Vostok, Antarctica', timezone: 'Antarctica/Vostok' },
    { id: 23, city: 'St. John\'s, Antigua and Barbuda', timezone: 'America/Antigua' },
    { id: 24, city: 'Buenos Aires, Argentina', timezone: 'America/Argentina/Buenos_Aires' },
    { id: 25, city: 'Catamarca, Argentina', timezone: 'America/Argentina/Catamarca' },
    { id: 26, city: 'Cordoba, Argentina', timezone: 'America/Argentina/Cordoba' },
    { id: 27, city: 'Jujuy, Argentina', timezone: 'America/Argentina/Jujuy' },
    { id: 28, city: 'La Rioja, Argentina', timezone: 'America/Argentina/La_Rioja' },
    { id: 29, city: 'Mendoza, Argentina', timezone: 'America/Argentina/Mendoza' },
    { id: 30, city: 'Rio Gallegos, Argentina', timezone: 'America/Argentina/Rio_Gallegos' },
    { id: 31, city: 'Salta, Argentina', timezone: 'America/Argentina/Salta' },
    { id: 32, city: 'San Juan, Argentina', timezone: 'America/Argentina/San_Juan' },
    { id: 33, city: 'San Luis, Argentina', timezone: 'America/Argentina/San_Luis' },
    { id: 34, city: 'Tucuman, Argentina', timezone: 'America/Argentina/Tucuman' },
    { id: 35, city: 'Ushuaia, Argentina', timezone: 'America/Argentina/Ushuaia' },
    { id: 36, city: 'Yerevan, Armenia', timezone: 'Asia/Yerevan' },
    { id: 37, city: 'Oranjestad, Aruba', timezone: 'America/Aruba' },
    { id: 38, city: 'Macquarie Island, Australia', timezone: 'Antarctica/Macquarie' },
    { id: 39, city: 'Adelaide, Australia', timezone: 'Australia/Adelaide' },
    { id: 40, city: 'Brisbane, Australia', timezone: 'Australia/Brisbane' },
    { id: 41, city: 'Broken Hill, Australia', timezone: 'Australia/Broken_Hill' },
    { id: 42, city: 'Darwin, Australia', timezone: 'Australia/Darwin' },
    { id: 43, city: 'Eucla, Australia', timezone: 'Australia/Eucla' },
    { id: 44, city: 'Hobart, Australia', timezone: 'Australia/Hobart' },
    { id: 45, city: 'Lindeman, Australia', timezone: 'Australia/Lindeman' },
    { id: 46, city: 'Lord Howe Island, Australia', timezone: 'Australia/Lord_Howe' },
    { id: 47, city: 'Melbourne, Australia', timezone: 'Australia/Melbourne' },
    { id: 48, city: 'Perth, Australia', timezone: 'Australia/Perth' },
    { id: 49, city: 'Sydney, Australia', timezone: 'Australia/Sydney' },
    { id: 50, city: 'Vienna, Austria', timezone: 'Europe/Vienna' },
    { id: 51, city: 'Baku, Azerbaijan', timezone: 'Asia/Baku' },
    { id: 52, city: 'Nassau, Bahamas', timezone: 'America/Nassau' },
    { id: 53, city: 'Manama, Bahrain', timezone: 'Asia/Bahrain' },
    { id: 54, city: 'Dhaka, Bangladesh', timezone: 'Asia/Dhaka' },
    { id: 55, city: 'Bridgetown, Barbados', timezone: 'America/Barbados' },
    { id: 56, city: 'Minsk, Belarus', timezone: 'Europe/Minsk' },
    { id: 57, city: 'Brussels, Belgium', timezone: 'Europe/Brussels' },
    { id: 58, city: 'Belize City, Belize', timezone: 'America/Belize' },
    { id: 59, city: 'Porto-Novo, Benin', timezone: 'Africa/Porto-Novo' },
    { id: 60, city: 'Hamilton, Bermuda', timezone: 'Atlantic/Bermuda' },
    { id: 61, city: 'Thimphu, Bhutan', timezone: 'Asia/Thimphu' },
    { id: 62, city: 'La Paz, Bolivia', timezone: 'America/La_Paz' },
    { id: 63, city: 'Kralendijk, Bonaire', timezone: 'America/Kralendijk' },
    { id: 64, city: 'Sarajevo, Bosnia and Herzegovina', timezone: 'Europe/Sarajevo' },
    { id: 65, city: 'Gaborone, Botswana', timezone: 'Africa/Gaborone' },
    { id: 66, city: 'Araguaina, Brazil', timezone: 'America/Araguaina' },
    { id: 67, city: 'Salvador, Brazil', timezone: 'America/Bahia' },
    { id: 68, city: 'Belem, Brazil', timezone: 'America/Belem' },
    { id: 69, city: 'Boa Vista, Brazil', timezone: 'America/Boa_Vista' },
    { id: 70, city: 'Campo Grande, Brazil', timezone: 'America/Campo_Grande' },
    { id: 71, city: 'Cuiaba, Brazil', timezone: 'America/Cuiaba' },
    { id: 72, city: 'Eirunepe, Brazil', timezone: 'America/Eirunepe' },
    { id: 73, city: 'Fortaleza, Brazil', timezone: 'America/Fortaleza' },
    { id: 74, city: 'Maceio, Brazil', timezone: 'America/Maceio' },
    { id: 75, city: 'Manaus, Brazil', timezone: 'America/Manaus' },
    { id: 76, city: 'Fernando de Noronha, Brazil', timezone: 'America/Noronha' },
    { id: 77, city: 'Porto Velho, Brazil', timezone: 'America/Porto_Velho' },
    { id: 78, city: 'Recife, Brazil', timezone: 'America/Recife' },
    { id: 79, city: 'Rio Branco, Brazil', timezone: 'America/Rio_Branco' },
    { id: 80, city: 'Santarem, Brazil', timezone: 'America/Santarem' },
    { id: 81, city: 'Sao Paulo, Brazil', timezone: 'America/Sao_Paulo' },
    { id: 82, city: 'Diego Garcia, British Indian Ocean Territory', timezone: 'Indian/Chagos' },
    { id: 83, city: 'Bandar Seri Begawan, Brunei', timezone: 'Asia/Brunei' },
    { id: 84, city: 'Sofia, Bulgaria', timezone: 'Europe/Sofia' },
    { id: 85, city: 'Ouagadougou, Burkina Faso', timezone: 'Africa/Ouagadougou' },
    { id: 86, city: 'Bujumbura, Burundi', timezone: 'Africa/Bujumbura' },
    { id: 87, city: 'Phnom Penh, Cambodia', timezone: 'Asia/Phnom_Penh' },
    { id: 88, city: 'Douala, Cameroon', timezone: 'Africa/Douala' },
    { id: 89, city: 'Atikokan, Canada', timezone: 'America/Atikokan' },
    { id: 90, city: 'Blanc-Sablon, Canada', timezone: 'America/Blanc-Sablon' },
    { id: 91, city: 'Cambridge Bay, Canada', timezone: 'America/Cambridge_Bay' },
    { id: 92, city: 'Creston, Canada', timezone: 'America/Creston' },
    { id: 93, city: 'Dawson, Canada', timezone: 'America/Dawson' },
    { id: 94, city: 'Dawson Creek, Canada', timezone: 'America/Dawson_Creek' },
    { id: 95, city: 'Edmonton, Canada', timezone: 'America/Edmonton' },
    { id: 96, city: 'Fort Nelson, Canada', timezone: 'America/Fort_Nelson' },
    { id: 97, city: 'Glace Bay, Canada', timezone: 'America/Glace_Bay' },
    { id: 98, city: 'Goose Bay, Canada', timezone: 'America/Goose_Bay' },
    { id: 99, city: 'Halifax, Canada', timezone: 'America/Halifax' },
    { id: 100, city: 'Inuvik, Canada', timezone: 'America/Inuvik' },
    { id: 101, city: 'Iqaluit, Canada', timezone: 'America/Iqaluit' },
    { id: 102, city: 'Moncton, Canada', timezone: 'America/Moncton' },
    { id: 103, city: 'Rankin Inlet, Canada', timezone: 'America/Rankin_Inlet' },
    { id: 104, city: 'Regina, Canada', timezone: 'America/Regina' },
    { id: 105, city: 'Resolute, Canada', timezone: 'America/Resolute' },
    { id: 106, city: 'St. John\'s, Canada', timezone: 'America/St_Johns' },
    { id: 107, city: 'Swift Current, Canada', timezone: 'America/Swift_Current' },
    { id: 108, city: 'Toronto, Canada', timezone: 'America/Toronto' },
    { id: 109, city: 'Vancouver, Canada', timezone: 'America/Vancouver' },
    { id: 110, city: 'Whitehorse, Canada', timezone: 'America/Whitehorse' },
    { id: 111, city: 'Winnipeg, Canada', timezone: 'America/Winnipeg' },
    { id: 112, city: 'Praia, Cape Verde', timezone: 'Atlantic/Cape_Verde' },
    { id: 113, city: 'George Town, Cayman Islands', timezone: 'America/Cayman' },
    { id: 114, city: 'Bangui, Central African Republic', timezone: 'Africa/Bangui' },
    { id: 115, city: 'N\'Djamena, Chad', timezone: 'Africa/Ndjamena' },
    { id: 116, city: 'Punta Arenas, Chile', timezone: 'America/Punta_Arenas' },
    { id: 117, city: 'Santiago, Chile', timezone: 'America/Santiago' },
    { id: 118, city: 'Easter Island, Chile', timezone: 'Pacific/Easter' },
    { id: 119, city: 'Shanghai, China', timezone: 'Asia/Shanghai' },
    { id: 120, city: 'Urumqi, China', timezone: 'Asia/Urumqi' },
    { id: 121, city: 'Flying Fish Cove, Christmas Island', timezone: 'Indian/Christmas' },
    { id: 122, city: 'West Island, Cocos (Keeling) Islands', timezone: 'Indian/Cocos' },
    { id: 123, city: 'Bogota, Colombia', timezone: 'America/Bogota' },
    { id: 124, city: 'Moroni, Comoros', timezone: 'Indian/Comoro' },
    { id: 125, city: 'Brazzaville, Congo', timezone: 'Africa/Brazzaville' },
    { id: 126, city: 'Kinshasa, Democratic Republic of the Congo', timezone: 'Africa/Kinshasa' },
    { id: 127, city: 'Lubumbashi, Democratic Republic of the Congo', timezone: 'Africa/Lubumbashi' },
    { id: 128, city: 'Rarotonga, Cook Islands', timezone: 'Pacific/Rarotonga' },
    { id: 129, city: 'San Jose, Costa Rica', timezone: 'America/Costa_Rica' },
    { id: 130, city: 'Zagreb, Croatia', timezone: 'Europe/Zagreb' },
    { id: 131, city: 'Havana, Cuba', timezone: 'America/Havana' },
    { id: 132, city: 'Willemstad, Curaçao', timezone: 'America/Curacao' },
    { id: 133, city: 'Famagusta, Cyprus', timezone: 'Asia/Famagusta' },
    { id: 134, city: 'Nicosia, Cyprus', timezone: 'Asia/Nicosia' },
    { id: 135, city: 'Prague, Czech Republic', timezone: 'Europe/Prague' },
    { id: 136, city: 'Abidjan, Côte d\'Ivoire', timezone: 'Africa/Abidjan' },
    { id: 137, city: 'Copenhagen, Denmark', timezone: 'Europe/Copenhagen' },
    { id: 138, city: 'Djibouti', timezone: 'Africa/Djibouti' },
    { id: 139, city: 'Roseau, Dominica', timezone: 'America/Dominica' },
    { id: 140, city: 'Santo Domingo, Dominican Republic', timezone: 'America/Santo_Domingo' },
    { id: 141, city: 'Guayaquil, Ecuador', timezone: 'America/Guayaquil' },
    { id: 142, city: 'Galapagos, Ecuador', timezone: 'Pacific/Galapagos' },
    { id: 143, city: 'Cairo, Egypt', timezone: 'Africa/Cairo' },
    { id: 144, city: 'San Salvador, El Salvador', timezone: 'America/El_Salvador' },
    { id: 145, city: 'Malabo, Equatorial Guinea', timezone: 'Africa/Malabo' },
    { id: 146, city: 'Asmara, Eritrea', timezone: 'Africa/Asmara' },
    { id: 147, city: 'Tallinn, Estonia', timezone: 'Europe/Tallinn' },
    { id: 148, city: 'Addis Ababa, Ethiopia', timezone: 'Africa/Addis_Ababa' },
    { id: 149, city: 'Stanley, Falkland Islands', timezone: 'Atlantic/Stanley' },
    { id: 150, city: 'Torshavn, Faroe Islands', timezone: 'Atlantic/Faroe' },
    { id: 151, city: 'Suva, Fiji', timezone: 'Pacific/Fiji' },
    { id: 152, city: 'Helsinki, Finland', timezone: 'Europe/Helsinki' },
    { id: 153, city: 'Paris, France', timezone: 'Europe/Paris' },
    { id: 154, city: 'Cayenne, French Guiana', timezone: 'America/Cayenne' },
    { id: 155, city: 'Gambier Islands, French Polynesia', timezone: 'Pacific/Gambier' },
    { id: 156, city: 'Marquesas Islands, French Polynesia', timezone: 'Pacific/Marquesas' },
    { id: 157, city: 'Papeete, French Polynesia', timezone: 'Pacific/Tahiti' },
    { id: 158, city: 'Kerguelen Islands, French Southern Territories', timezone: 'Indian/Kerguelen' },
    { id: 159, city: 'Libreville, Gabon', timezone: 'Africa/Libreville' },
    { id: 160, city: 'Banjul, Gambia', timezone: 'Africa/Banjul' },
    { id: 161, city: 'Tbilisi, Georgia', timezone: 'Asia/Tbilisi' },
    { id: 162, city: 'Berlin, Germany', timezone: 'Europe/Berlin' },
    { id: 163, city: 'Busingen, Germany', timezone: 'Europe/Busingen' },
    { id: 164, city: 'Accra, Ghana', timezone: 'Africa/Accra' },
    { id: 165, city: 'Gibraltar', timezone: 'Europe/Gibraltar' },
    { id: 166, city: 'Athens, Greece', timezone: 'Europe/Athens' },
    { id: 167, city: 'Danmarkshavn, Greenland', timezone: 'America/Danmarkshavn' },
    { id: 168, city: 'Nuuk, Greenland', timezone: 'America/Nuuk' },
    { id: 169, city: 'Scoresbysund, Greenland', timezone: 'America/Scoresbysund' },
    { id: 170, city: 'Thule, Greenland', timezone: 'America/Thule' },
    { id: 171, city: 'St. George\'s, Grenada', timezone: 'America/Grenada' },
    { id: 172, city: 'Basse-Terre, Guadeloupe', timezone: 'America/Guadeloupe' },
    { id: 173, city: 'Hagåtña, Guam', timezone: 'Pacific/Guam' },
    { id: 174, city: 'Guatemala City, Guatemala', timezone: 'America/Guatemala' },
    { id: 175, city: 'St. Peter Port, Guernsey', timezone: 'Europe/Guernsey' },
    { id: 176, city: 'Conakry, Guinea', timezone: 'Africa/Conakry' },
    { id: 177, city: 'Bissau, Guinea-Bissau', timezone: 'Africa/Bissau' },
    { id: 178, city: 'Georgetown, Guyana', timezone: 'America/Guyana' },
    { id: 179, city: 'Port-au-Prince, Haiti', timezone: 'America/Port-au-Prince' },
    { id: 180, city: 'Vatican City', timezone: 'Europe/Vatican' },
    { id: 181, city: 'Tegucigalpa, Honduras', timezone: 'America/Tegucigalpa' },
    { id: 182, city: 'Hong Kong', timezone: 'Asia/Hong_Kong' },
    { id: 183, city: 'Budapest, Hungary', timezone: 'Europe/Budapest' },
    { id: 184, city: 'Reykjavik, Iceland', timezone: 'Atlantic/Reykjavik' },
    { id: 185, city: 'New Delhi, India', timezone: 'Asia/Kolkata' },
    { id: 186, city: 'Jakarta, Indonesia', timezone: 'Asia/Jakarta' },
    { id: 187, city: 'Jayapura, Indonesia', timezone: 'Asia/Jayapura' },
    { id: 188, city: 'Makassar, Indonesia', timezone: 'Asia/Makassar' },
    { id: 189, city: 'Pontianak, Indonesia', timezone: 'Asia/Pontianak' },
    { id: 190, city: 'Tehran, Iran', timezone: 'Asia/Tehran' },
    { id: 191, city: 'Baghdad, Iraq', timezone: 'Asia/Baghdad' },
    { id: 192, city: 'Dublin, Ireland', timezone: 'Europe/Dublin' },
    { id: 193, city: 'Douglas, Isle of Man', timezone: 'Europe/Isle_of_Man' },
    { id: 194, city: 'Jerusalem, Israel', timezone: 'Asia/Jerusalem' },
    { id: 195, city: 'Rome, Italy', timezone: 'Europe/Rome' },
    { id: 196, city: 'Kingston, Jamaica', timezone: 'America/Jamaica' },
    { id: 197, city: 'Tokyo, Japan', timezone: 'Asia/Tokyo' },
    { id: 198, city: 'St. Helier, Jersey', timezone: 'Europe/Jersey' },
    { id: 199, city: 'Amman, Jordan', timezone: 'Asia/Amman' },
    { id: 200, city: 'Almaty, Kazakhstan', timezone: 'Asia/Almaty' },
    { id: 201, city: 'Aqtau, Kazakhstan', timezone: 'Asia/Aqtau' },
    { id: 202, city: 'Aqtobe, Kazakhstan', timezone: 'Asia/Aqtobe' },
    { id: 203, city: 'Atyrau, Kazakhstan', timezone: 'Asia/Atyrau' },
    { id: 204, city: 'Oral, Kazakhstan', timezone: 'Asia/Oral' },
    { id: 205, city: 'Qostanay, Kazakhstan', timezone: 'Asia/Qostanay' },
    { id: 206, city: 'Qyzylorda, Kazakhstan', timezone: 'Asia/Qyzylorda' },
    { id: 207, city: 'Nairobi, Kenya', timezone: 'Africa/Nairobi' },
    { id: 208, city: 'Tarawa, Kiribati', timezone: 'Pacific/Tarawa' },
    { id: 209, city: 'Kiritimati, Kiribati', timezone: 'Pacific/Kiritimati' },
    { id: 210, city: 'Pyongyang, North Korea', timezone: 'Asia/Pyongyang' },
    { id: 211, city: 'Seoul, South Korea', timezone: 'Asia/Seoul' },
    { id: 212, city: 'Kuwait City, Kuwait', timezone: 'Asia/Kuwait' },
    { id: 213, city: 'Bishkek, Kyrgyzstan', timezone: 'Asia/Bishkek' },
    { id: 214, city: 'Vientiane, Laos', timezone: 'Asia/Vientiane' },
    { id: 215, city: 'Riga, Latvia', timezone: 'Europe/Riga' },
    { id: 216, city: 'Beirut, Lebanon', timezone: 'Asia/Beirut' },
    { id: 217, city: 'Maseru, Lesotho', timezone: 'Africa/Maseru' },
    { id: 218, city: 'Monrovia, Liberia', timezone: 'Africa/Monrovia' },
    { id: 219, city: 'Tripoli, Libya', timezone: 'Africa/Tripoli' },
    { id: 220, city: 'Vaduz, Liechtenstein', timezone: 'Europe/Vaduz' },
    { id: 221, city: 'Vilnius, Lithuania', timezone: 'Europe/Vilnius' },
    { id: 222, city: 'Luxembourg City, Luxembourg', timezone: 'Europe/Luxembourg' },
    { id: 223, city: 'Macau', timezone: 'Asia/Macau' },
    { id: 224, city: 'Skopje, North Macedonia', timezone: 'Europe/Skopje' },
    { id: 225, city: 'Antananarivo, Madagascar', timezone: 'Indian/Antananarivo' },
    { id: 226, city: 'Lilongwe, Malawi', timezone: 'Africa/Blantyre' },
    { id: 227, city: 'Kuala Lumpur, Malaysia', timezone: 'Asia/Kuala_Lumpur' },
    { id: 228, city: 'Kuching, Malaysia', timezone: 'Asia/Kuching' },
    { id: 229, city: 'Male, Maldives', timezone: 'Indian/Maldives' },
    { id: 230, city: 'Bamako, Mali', timezone: 'Africa/Bamako' },
    { id: 231, city: 'Valletta, Malta', timezone: 'Europe/Malta' },
    { id: 232, city: 'Majuro, Marshall Islands', timezone: 'Pacific/Majuro' },
    { id: 233, city: 'Fort-de-France, Martinique', timezone: 'America/Martinique' },
    { id: 234, city: 'Nouakchott, Mauritania', timezone: 'Africa/Nouakchott' },
    { id: 235, city: 'Port Louis, Mauritius', timezone: 'Indian/Mauritius' },
    { id: 236, city: 'Mamoudzou, Mayotte', timezone: 'Indian/Mayotte' },
    { id: 237, city: 'Mexico City, Mexico', timezone: 'America/Mexico_City' },
    { id: 238, city: 'Palikir, Micronesia', timezone: 'Pacific/Pohnpei' },
    { id: 239, city: 'Chisinau, Moldova', timezone: 'Europe/Chisinau' },
    { id: 240, city: 'Monaco', timezone: 'Europe/Monaco' },
    { id: 241, city: 'Ulaanbaatar, Mongolia', timezone: 'Asia/Ulaanbaatar' },
    { id: 242, city: 'Podgorica, Montenegro', timezone: 'Europe/Podgorica' },
    { id: 243, city: 'Plymouth, Montserrat', timezone: 'America/Montserrat' },
    { id: 244, city: 'Casablanca, Morocco', timezone: 'Africa/Casablanca' },
    { id: 245, city: 'Maputo, Mozambique', timezone: 'Africa/Maputo' },
    { id: 246, city: 'Yangon, Myanmar', timezone: 'Asia/Yangon' },
    { id: 247, city: 'Windhoek, Namibia', timezone: 'Africa/Windhoek' },
    { id: 248, city: 'Yaren, Nauru', timezone: 'Pacific/Nauru' },
    { id: 249, city: 'Kathmandu, Nepal', timezone: 'Asia/Kathmandu' },
    { id: 250, city: 'Amsterdam, Netherlands', timezone: 'Europe/Amsterdam' },
    { id: 251, city: 'Noumea, New Caledonia', timezone: 'Pacific/Noumea' },
    { id: 252, city: 'Wellington, New Zealand', timezone: 'Pacific/Auckland' },
    { id: 253, city: 'Managua, Nicaragua', timezone: 'America/Managua' },
    { id: 254, city: 'Niamey, Niger', timezone: 'Africa/Niamey' },
    { id: 255, city: 'Lagos, Nigeria', timezone: 'Africa/Lagos' },
    { id: 256, city: 'Alofi, Niue', timezone: 'Pacific/Niue' },
    { id: 257, city: 'Kingston, Norfolk Island', timezone: 'Pacific/Norfolk' },
    { id: 258, city: 'Saipan, Northern Mariana Islands', timezone: 'Pacific/Saipan' },
    { id: 259, city: 'Oslo, Norway', timezone: 'Europe/Oslo' },
    { id: 260, city: 'Muscat, Oman', timezone: 'Asia/Muscat' },
    { id: 261, city: 'Karachi, Pakistan', timezone: 'Asia/Karachi' },
    { id: 262, city: 'Ngerulmud, Palau', timezone: 'Pacific/Palau' },
    { id: 263, city: 'Gaza, Palestine', timezone: 'Asia/Gaza' },
    { id: 264, city: 'Panama City, Panama', timezone: 'America/Panama' },
    { id: 265, city: 'Port Moresby, Papua New Guinea', timezone: 'Pacific/Port_Moresby' },
    { id: 266, city: 'Asunción, Paraguay', timezone: 'America/Asuncion' },
    { id: 267, city: 'Lima, Peru', timezone: 'America/Lima' },
    { id: 268, city: 'Manila, Philippines', timezone: 'Asia/Manila' },
    { id: 269, city: 'Adamstown, Pitcairn', timezone: 'Pacific/Pitcairn' },
    { id: 270, city: 'Warsaw, Poland', timezone: 'Europe/Warsaw' },
    { id: 271, city: 'Lisbon, Portugal', timezone: 'Europe/Lisbon' },
    { id: 272, city: 'San Juan, Puerto Rico', timezone: 'America/Puerto_Rico' },
    { id: 273, city: 'Doha, Qatar', timezone: 'Asia/Qatar' },
    { id: 274, city: 'Bucharest, Romania', timezone: 'Europe/Bucharest' },
    { id: 275, city: 'Moscow, Russia', timezone: 'Europe/Moscow' },
    { id: 276, city: 'Kigali, Rwanda', timezone: 'Africa/Kigali' },
    { id: 277, city: 'Saint-Denis, Réunion', timezone: 'Indian/Reunion' },
    { id: 278, city: 'Gustavia, Saint Barthélemy', timezone: 'America/St_Barthelemy' },
    { id: 279, city: 'Jamestown, Saint Helena', timezone: 'Atlantic/St_Helena' },
    { id: 280, city: 'Basseterre, Saint Kitts and Nevis', timezone: 'America/St_Kitts' },
    { id: 281, city: 'Castries, Saint Lucia', timezone: 'America/St_Lucia' },
    { id: 282, city: 'Marigot, Saint Martin', timezone: 'America/Marigot' },
    { id: 283, city: 'Saint-Pierre, Saint Pierre and Miquelon', timezone: 'America/Miquelon' },
    { id: 284, city: 'Kingstown, Saint Vincent and the Grenadines', timezone: 'America/St_Vincent' },
    { id: 285, city: 'Apia, Samoa', timezone: 'Pacific/Apia' },
    { id: 286, city: 'San Marino', timezone: 'Europe/San_Marino' },
    { id: 287, city: 'São Tomé, Sao Tome and Principe', timezone: 'Africa/Sao_Tome' },
    { id: 288, city: 'Riyadh, Saudi Arabia', timezone: 'Asia/Riyadh' },
    { id: 289, city: 'Dakar, Senegal', timezone: 'Africa/Dakar' },
    { id: 290, city: 'Belgrade, Serbia', timezone: 'Europe/Belgrade' },
    { id: 291, city: 'Victoria, Seychelles', timezone: 'Indian/Mahe' },
    { id: 292, city: 'Freetown, Sierra Leone', timezone: 'Africa/Freetown' },
    { id: 293, city: 'Singapore', timezone: 'Asia/Singapore' },
    { id: 294, city: 'Philipsburg, Sint Maarten', timezone: 'America/Lower_Princes' },
    { id: 295, city: 'Bratislava, Slovakia', timezone: 'Europe/Bratislava' },
    { id: 296, city: 'Ljubljana, Slovenia', timezone: 'Europe/Ljubljana' },
    { id: 297, city: 'Honiara, Solomon Islands', timezone: 'Pacific/Guadalcanal' },
    { id: 298, city: 'Mogadishu, Somalia', timezone: 'Africa/Mogadishu' },
    { id: 299, city: 'Pretoria, South Africa', timezone: 'Africa/Johannesburg' },
    { id: 300, city: 'King Edward Point, South Georgia and the South Sandwich Islands', timezone: 'Atlantic/South_Georgia' },
    { id: 301, city: 'Juba, South Sudan', timezone: 'Africa/Juba' },
    { id: 302, city: 'Madrid, Spain', timezone: 'Europe/Madrid' },
    { id: 303, city: 'Colombo, Sri Lanka', timezone: 'Asia/Colombo' },
    { id: 304, city: 'Khartoum, Sudan', timezone: 'Africa/Khartoum' },
    { id: 305, city: 'Paramaribo, Suriname', timezone: 'America/Paramaribo' },
    { id: 306, city: 'Longyearbyen, Svalbard and Jan Mayen', timezone: 'Arctic/Longyearbyen' },
    { id: 307, city: 'Stockholm, Sweden', timezone: 'Europe/Stockholm' },
    { id: 308, city: 'Zurich, Switzerland', timezone: 'Europe/Zurich' },
    { id: 309, city: 'Damascus, Syria', timezone: 'Asia/Damascus' },
    { id: 310, city: 'Taipei, Taiwan', timezone: 'Asia/Taipei' },
    { id: 311, city: 'Dushanbe, Tajikistan', timezone: 'Asia/Dushanbe' },
    { id: 312, city: 'Dar es Salaam, Tanzania', timezone: 'Africa/Dar_es_Salaam' },
    { id: 313, city: 'Bangkok, Thailand', timezone: 'Asia/Bangkok' },
    { id: 314, city: 'Dili, Timor-Leste', timezone: 'Asia/Dili' },
    { id: 315, city: 'Lome, Togo', timezone: 'Africa/Lome' },
    { id: 316, city: 'Fakaofo, Tokelau', timezone: 'Pacific/Fakaofo' },
    { id: 317, city: 'Nuku\'alofa, Tonga', timezone: 'Pacific/Tongatapu' },
    { id: 318, city: 'Port of Spain, Trinidad and Tobago', timezone: 'America/Port_of_Spain' },
    { id: 319, city: 'Tunis, Tunisia', timezone: 'Africa/Tunis' },
    { id: 320, city: 'Istanbul, Turkey', timezone: 'Europe/Istanbul' },
    { id: 321, city: 'Ashgabat, Turkmenistan', timezone: 'Asia/Ashgabat' },
    { id: 322, city: 'Cockburn Town, Turks and Caicos Islands', timezone: 'America/Grand_Turk' },
    { id: 323, city: 'Funafuti, Tuvalu', timezone: 'Pacific/Funafuti' },
    { id: 324, city: 'Kampala, Uganda', timezone: 'Africa/Kampala' },
    { id: 325, city: 'Kyiv, Ukraine', timezone: 'Europe/Kiev' },
    { id: 326, city: 'Abu Dhabi, United Arab Emirates', timezone: 'Asia/Dubai' },
    { id: 327, city: 'London, United Kingdom', timezone: 'Europe/London' },
    { id: 328, city: 'New York, United States', timezone: 'America/New_York' },
    { id: 329, city: 'Montevideo, Uruguay', timezone: 'America/Montevideo' },
    { id: 330, city: 'Tashkent, Uzbekistan', timezone: 'Asia/Tashkent' },
    { id: 331, city: 'Port Vila, Vanuatu', timezone: 'Pacific/Efate' },
    { id: 332, city: 'Caracas, Venezuela', timezone: 'America/Caracas' },
    { id: 333, city: 'Hanoi, Vietnam', timezone: 'Asia/Ho_Chi_Minh' },
    { id: 334, city: 'Road Town, British Virgin Islands', timezone: 'America/Tortola' },
    { id: 335, city: 'Charlotte Amalie, U.S. Virgin Islands', timezone: 'America/St_Thomas' },
    { id: 336, city: 'Mata-Utu, Wallis and Futuna', timezone: 'Pacific/Wallis' },
    { id: 337, city: 'El Aaiún, Western Sahara', timezone: 'Africa/El_Aaiun' },
    { id: 338, city: 'Sana\'a, Yemen', timezone: 'Asia/Aden' },
    { id: 339, city: 'Lusaka, Zambia', timezone: 'Africa/Lusaka' },
    { id: 340, city: 'Harare, Zimbabwe', timezone: 'Africa/Harare' },
    { id: 341, city: 'Mariehamn, Åland Islands', timezone: 'Europe/Mariehamn' },
    // add hawaii
    { id: 342, city: 'Honolulu, Hawaii', timezone: 'Pacific/Honolulu' },
    // add alaska
    { id: 343, city: 'Anchorage, Alaska', timezone: 'America/Anchorage' },
    // add pacific
    { id: 344, city: 'Los Angeles, Pacific', timezone: 'America/Los_Angeles' },
];