export interface CityData {
    id: number;
    city: string;
    cityName: string;
    countryLocation: string;
    timezone: string;
}
export const timezoneData:CityData[] = [
    { id: 6, city: 'Kabul, Afghanistan', cityName: 'Kabul', countryLocation: 'Afghanistan', timezone: 'Asia/Kabul' },
    { id: 7, city: 'Tirana, Albania', cityName: 'Tirana', countryLocation: 'Albania', timezone: 'Europe/Tirane' },
    { id: 8, city: 'Algiers, Algeria', cityName: 'Algiers', countryLocation: 'Algeria', timezone: 'Africa/Algiers' },
    { id: 9, city: 'Pago Pago, American Samoa', cityName: 'Pago Pago', countryLocation: 'American Samoa', timezone: 'Pacific/Pago_Pago' },
    { id: 10, city: 'Andorra la Vella, Andorra', cityName: 'Andorra la Vella', countryLocation: 'Andorra', timezone: 'Europe/Andorra' },
    { id: 11, city: 'Luanda, Angola', cityName: 'Luanda', countryLocation: 'Angola', timezone: 'Africa/Luanda' },
    { id: 12, city: 'The Valley, Anguilla', cityName: 'The Valley', countryLocation: 'Anguilla', timezone: 'America/Anguilla' },
    { id: 13, city: 'Casey, Antarctica', cityName: 'Casey', countryLocation: 'Antarctica', timezone: 'Antarctica/Casey' },
    { id: 14, city: 'Davis, Antarctica', cityName: 'Davis', countryLocation: 'Antarctica', timezone: 'Antarctica/Davis' },
    { id: 15, city: 'Dumont d\'Urville, Antarctica', cityName: 'Dumont d\'Urville', countryLocation: 'Antarctica', timezone: 'Antarctica/DumontDUrville' },
    { id: 16, city: 'Mawson, Antarctica', cityName: 'Mawson', countryLocation: 'Antarctica', timezone: 'Antarctica/Mawson' },
    { id: 17, city: 'McMurdo, Antarctica', cityName: 'McMurdo', countryLocation: 'Antarctica', timezone: 'Antarctica/McMurdo' },
    { id: 18, city: 'Palmer, Antarctica', cityName: 'Palmer', countryLocation: 'Antarctica', timezone: 'Antarctica/Palmer' },
    { id: 19, city: 'Rothera, Antarctica', cityName: 'Rothera', countryLocation: 'Antarctica', timezone: 'Antarctica/Rothera' },
    { id: 20, city: 'Syowa, Antarctica', cityName: 'Syowa', countryLocation: 'Antarctica', timezone: 'Antarctica/Syowa' },
    { id: 21, city: 'Troll, Antarctica', cityName: 'Troll', countryLocation: 'Antarctica', timezone: 'Antarctica/Troll' },
    { id: 22, city: 'Vostok, Antarctica', cityName: 'Vostok', countryLocation: 'Antarctica', timezone: 'Antarctica/Vostok' },
    { id: 23, city: 'St. John\'s, Antigua and Barbuda', cityName: 'St. John\'s', countryLocation: 'Antigua and Barbuda', timezone: 'America/Antigua' },
    { id: 24, city: 'Buenos Aires, Argentina', cityName: 'Buenos Aires', countryLocation: 'Argentina', timezone: 'America/Argentina/Buenos_Aires' },
    { id: 25, city: 'Catamarca, Argentina', cityName: 'Catamarca', countryLocation: 'Argentina', timezone: 'America/Argentina/Catamarca' },
    { id: 26, city: 'Cordoba, Argentina', cityName: 'Cordoba', countryLocation: 'Argentina', timezone: 'America/Argentina/Cordoba' },
    { id: 27, city: 'Jujuy, Argentina', cityName: 'Jujuy', countryLocation: 'Argentina', timezone: 'America/Argentina/Jujuy' },
    { id: 28, city: 'La Rioja, Argentina', cityName: 'La Rioja', countryLocation: 'Argentina', timezone: 'America/Argentina/La_Rioja' },
    { id: 29, city: 'Mendoza, Argentina', cityName: 'Mendoza', countryLocation: 'Argentina', timezone: 'America/Argentina/Mendoza' },
    { id: 30, city: 'Rio Gallegos, Argentina', cityName: 'Rio Gallegos', countryLocation: 'Argentina', timezone: 'America/Argentina/Rio_Gallegos' },
    { id: 31, city: 'Salta, Argentina', cityName: 'Salta', countryLocation: 'Argentina', timezone: 'America/Argentina/Salta' },
    { id: 32, city: 'San Juan, Argentina', cityName: 'San Juan', countryLocation: 'Argentina', timezone: 'America/Argentina/San_Juan' },
    { id: 33, city: 'San Luis, Argentina', cityName: 'San Luis', countryLocation: 'Argentina', timezone: 'America/Argentina/San_Luis' },
    { id: 34, city: 'Tucuman, Argentina', cityName: 'Tucuman', countryLocation: 'Argentina', timezone: 'America/Argentina/Tucuman' },
    { id: 35, city: 'Ushuaia, Argentina', cityName: 'Ushuaia', countryLocation: 'Argentina', timezone: 'America/Argentina/Ushuaia' },
    { id: 36, city: 'Yerevan, Armenia', cityName: 'Yerevan', countryLocation: 'Armenia', timezone: 'Asia/Yerevan' },
    { id: 37, city: 'Oranjestad, Aruba', cityName: 'Oranjestad', countryLocation: 'Aruba', timezone: 'America/Aruba' },
    { id: 38, city: 'Macquarie Island, Australia', cityName: 'Macquarie Island', countryLocation: 'Australia', timezone: 'Antarctica/Macquarie' },
    { id: 39, city: 'Adelaide, Australia', cityName: 'Adelaide', countryLocation: 'Australia', timezone: 'Australia/Adelaide' },
    { id: 40, city: 'Brisbane, Australia', cityName: 'Brisbane', countryLocation: 'Australia', timezone: 'Australia/Brisbane' },
    { id: 41, city: 'Broken Hill, Australia', cityName: 'Broken Hill', countryLocation: 'Australia', timezone: 'Australia/Broken_Hill' },
    { id: 42, city: 'Darwin, Australia', cityName: 'Darwin', countryLocation: 'Australia', timezone: 'Australia/Darwin' },
    { id: 43, city: 'Eucla, Australia', cityName: 'Eucla', countryLocation: 'Australia', timezone: 'Australia/Eucla' },
    { id: 44, city: 'Hobart, Australia', cityName: 'Hobart', countryLocation: 'Australia', timezone: 'Australia/Hobart' },
    { id: 45, city: 'Lindeman, Australia', cityName: 'Lindeman', countryLocation: 'Australia', timezone: 'Australia/Lindeman' },
    { id: 46, city: 'Lord Howe Island, Australia', cityName: 'Lord Howe Island', countryLocation: 'Australia', timezone: 'Australia/Lord_Howe' },
    { id: 47, city: 'Melbourne, Australia', cityName: 'Melbourne', countryLocation: 'Australia', timezone: 'Australia/Melbourne' },
    { id: 48, city: 'Perth, Australia', cityName: 'Perth', countryLocation: 'Australia', timezone: 'Australia/Perth' },
    { id: 49, city: 'Sydney, Australia', cityName: 'Sydney', countryLocation: 'Australia', timezone: 'Australia/Sydney' },
    { id: 50, city: 'Vienna, Austria', cityName: 'Vienna', countryLocation: 'Austria', timezone: 'Europe/Vienna' },
    { id: 51, city: 'Baku, Azerbaijan', cityName: 'Baku', countryLocation: 'Azerbaijan', timezone: 'Asia/Baku' },
    { id: 52, city: 'Nassau, Bahamas', cityName: 'Nassau', countryLocation: 'Bahamas', timezone: 'America/Nassau' },
    { id: 53, city: 'Manama, Bahrain', cityName: 'Manama', countryLocation: 'Bahrain', timezone: 'Asia/Bahrain' },
    { id: 54, city: 'Dhaka, Bangladesh', cityName: 'Dhaka', countryLocation: 'Bangladesh', timezone: 'Asia/Dhaka' },
    { id: 55, city: 'Bridgetown, Barbados', cityName: 'Bridgetown', countryLocation: 'Barbados', timezone: 'America/Barbados' },
    { id: 56, city: 'Minsk, Belarus', cityName: 'Minsk', countryLocation: 'Belarus', timezone: 'Europe/Minsk' },
    { id: 57, city: 'Brussels, Belgium', cityName: 'Brussels', countryLocation: 'Belgium', timezone: 'Europe/Brussels' },
    { id: 58, city: 'Belize City, Belize', cityName: 'Belize City', countryLocation: 'Belize', timezone: 'America/Belize' },
    { id: 59, city: 'Porto-Novo, Benin', cityName: 'Porto-Novo', countryLocation: 'Benin', timezone: 'Africa/Porto-Novo' },
    { id: 60, city: 'Hamilton, Bermuda', cityName: 'Hamilton', countryLocation: 'Bermuda', timezone: 'Atlantic/Bermuda' },
    { id: 61, city: 'Thimphu, Bhutan', cityName: 'Thimphu', countryLocation: 'Bhutan', timezone: 'Asia/Thimphu' },
    { id: 62, city: 'La Paz, Bolivia', cityName: 'La Paz', countryLocation: 'Bolivia', timezone: 'America/La_Paz' },
    { id: 63, city: 'Kralendijk, Bonaire', cityName: 'Kralendijk', countryLocation: 'Bonaire', timezone: 'America/Kralendijk' },
    { id: 64, city: 'Sarajevo, Bosnia and Herzegovina', cityName: 'Sarajevo', countryLocation: 'Bosnia and Herzegovina', timezone: 'Europe/Sarajevo' },
    { id: 65, city: 'Gaborone, Botswana', cityName: 'Gaborone', countryLocation: 'Botswana', timezone: 'Africa/Gaborone' },
    { id: 66, city: 'Araguaina, Brazil', cityName: 'Araguaina', countryLocation: 'Brazil', timezone: 'America/Araguaina' },
    { id: 67, city: 'Salvador, Brazil', cityName: 'Salvador', countryLocation: 'Brazil', timezone: 'America/Bahia' },
    { id: 68, city: 'Belem, Brazil', cityName: 'Belem', countryLocation: 'Brazil', timezone: 'America/Belem' },
    { id: 69, city: 'Boa Vista, Brazil', cityName: 'Boa Vista', countryLocation: 'Brazil', timezone: 'America/Boa_Vista' },
    { id: 70, city: 'Campo Grande, Brazil', cityName: 'Campo Grande', countryLocation: 'Brazil', timezone: 'America/Campo_Grande' },
    { id: 71, city: 'Cuiaba, Brazil', cityName: 'Cuiaba', countryLocation: 'Brazil', timezone: 'America/Cuiaba' },
    { id: 72, city: 'Eirunepe, Brazil', cityName: 'Eirunepe', countryLocation: 'Brazil', timezone: 'America/Eirunepe' },
    { id: 73, city: 'Fortaleza, Brazil', cityName: 'Fortaleza', countryLocation: 'Brazil', timezone: 'America/Fortaleza' },
    { id: 74, city: 'Maceio, Brazil', cityName: 'Maceio', countryLocation: 'Brazil', timezone: 'America/Maceio' },
    { id: 75, city: 'Manaus, Brazil', cityName: 'Manaus', countryLocation: 'Brazil', timezone: 'America/Manaus' },
    { id: 76, city: 'Fernando de Noronha, Brazil', cityName: 'Fernando de Noronha', countryLocation: 'Brazil', timezone: 'America/Noronha' },
    { id: 77, city: 'Porto Velho, Brazil', cityName: 'Porto Velho', countryLocation: 'Brazil', timezone: 'America/Porto_Velho' },
    { id: 78, city: 'Recife, Brazil', cityName: 'Recife', countryLocation: 'Brazil', timezone: 'America/Recife' },
    { id: 79, city: 'Rio Branco, Brazil', cityName: 'Rio Branco', countryLocation: 'Brazil', timezone: 'America/Rio_Branco' },
    { id: 80, city: 'Santarem, Brazil', cityName: 'Santarem', countryLocation: 'Brazil', timezone: 'America/Santarem' },
    { id: 81, city: 'Sao Paulo, Brazil', cityName: 'Sao Paulo', countryLocation: 'Brazil', timezone: 'America/Sao_Paulo' },
    { id: 82, city: 'Diego Garcia, British Indian Ocean Territory', cityName: 'Diego Garcia', countryLocation: 'British Indian Ocean Territory', timezone: 'Indian/Chagos' },
    { id: 83, city: 'Bandar Seri Begawan, Brunei', cityName: 'Bandar Seri Begawan', countryLocation: 'Brunei', timezone: 'Asia/Brunei' },
    { id: 84, city: 'Sofia, Bulgaria', cityName: 'Sofia', countryLocation: 'Bulgaria', timezone: 'Europe/Sofia' },
    { id: 85, city: 'Ouagadougou, Burkina Faso', cityName: 'Ouagadougou', countryLocation: 'Burkina Faso', timezone: 'Africa/Ouagadougou' },
    { id: 86, city: 'Bujumbura, Burundi', cityName: 'Bujumbura', countryLocation: 'Burundi', timezone: 'Africa/Bujumbura' },
    { id: 87, city: 'Phnom Penh, Cambodia', cityName: 'Phnom Penh', countryLocation: 'Cambodia', timezone: 'Asia/Phnom_Penh' },
    { id: 88, city: 'Douala, Cameroon', cityName: 'Douala', countryLocation: 'Cameroon', timezone: 'Africa/Douala' },
    { id: 89, city: 'Atikokan, Canada', cityName: 'Atikokan', countryLocation: 'Canada', timezone: 'America/Atikokan' },
    { id: 90, city: 'Blanc-Sablon, Canada', cityName: 'Blanc-Sablon', countryLocation: 'Canada', timezone: 'America/Blanc-Sablon' },
    { id: 91, city: 'Cambridge Bay, Canada', cityName: 'Cambridge Bay', countryLocation: 'Canada', timezone: 'America/Cambridge_Bay' },
    { id: 92, city: 'Creston, Canada', cityName: 'Creston', countryLocation: 'Canada', timezone: 'America/Creston' },
    { id: 93, city: 'Dawson, Canada', cityName: 'Dawson', countryLocation: 'Canada', timezone: 'America/Dawson' },
    { id: 94, city: 'Dawson Creek, Canada', cityName: 'Dawson Creek', countryLocation: 'Canada', timezone: 'America/Dawson_Creek' },
    { id: 95, city: 'Edmonton, Canada', cityName: 'Edmonton', countryLocation: 'Canada', timezone: 'America/Edmonton' },
    { id: 96, city: 'Fort Nelson, Canada', cityName: 'Fort Nelson', countryLocation: 'Canada', timezone: 'America/Fort_Nelson' },
    { id: 97, city: 'Glace Bay, Canada', cityName: 'Glace Bay', countryLocation: 'Canada', timezone: 'America/Glace_Bay' },
    { id: 98, city: 'Goose Bay, Canada', cityName: 'Goose Bay', countryLocation: 'Canada', timezone: 'America/Goose_Bay' },
    { id: 99, city: 'Halifax, Canada', cityName: 'Halifax', countryLocation: 'Canada', timezone: 'America/Halifax' },
    { id: 100, city: 'Inuvik, Canada', cityName: 'Inuvik', countryLocation: 'Canada', timezone: 'America/Inuvik' },
    { id: 101, city: 'Iqaluit, Canada', cityName: 'Iqaluit', countryLocation: 'Canada', timezone: 'America/Iqaluit' },
    { id: 102, city: 'Moncton, Canada', cityName: 'Moncton', countryLocation: 'Canada', timezone: 'America/Moncton' },
    { id: 103, city: 'Rankin Inlet, Canada', cityName: 'Rankin Inlet', countryLocation: 'Canada', timezone: 'America/Rankin_Inlet' },
    { id: 104, city: 'Regina, Canada', cityName: 'Regina', countryLocation: 'Canada', timezone: 'America/Regina' },
    { id: 105, city: 'Resolute, Canada', cityName: 'Resolute', countryLocation: 'Canada', timezone: 'America/Resolute' },
    { id: 106, city: 'St. John\'s, Canada', cityName: 'St. John\'s', countryLocation: 'Canada', timezone: 'America/St_Johns' },
    { id: 107, city: 'Swift Current, Canada', cityName: 'Swift Current', countryLocation: 'Canada', timezone: 'America/Swift_Current' },
    { id: 108, city: 'Toronto, Canada', cityName: 'Toronto', countryLocation: 'Canada', timezone: 'America/Toronto' },
    { id: 109, city: 'Vancouver, Canada', cityName: 'Vancouver', countryLocation: 'Canada', timezone: 'America/Vancouver' },
    { id: 110, city: 'Whitehorse, Canada', cityName: 'Whitehorse', countryLocation: 'Canada', timezone: 'America/Whitehorse' },
    { id: 111, city: 'Winnipeg, Canada', cityName: 'Winnipeg', countryLocation: 'Canada', timezone: 'America/Winnipeg' },
    { id: 112, city: 'Praia, Cape Verde', cityName: 'Praia', countryLocation: 'Cape Verde', timezone: 'Atlantic/Cape_Verde' },
    { id: 113, city: 'George Town, Cayman Islands', cityName: 'George Town', countryLocation: 'Cayman Islands', timezone: 'America/Cayman' },
    { id: 114, city: 'Bangui, Central African Republic', cityName: 'Bangui', countryLocation: 'Central African Republic', timezone: 'Africa/Bangui' },
    { id: 115, city: 'N\'Djamena, Chad', cityName: 'N\'Djamena', countryLocation: 'Chad', timezone: 'Africa/Ndjamena' },
    { id: 116, city: 'Punta Arenas, Chile', cityName: 'Punta Arenas', countryLocation: 'Chile', timezone: 'America/Punta_Arenas' },
    { id: 117, city: 'Santiago, Chile', cityName: 'Santiago', countryLocation: 'Chile', timezone: 'America/Santiago' },
    { id: 118, city: 'Easter Island, Chile', cityName: 'Easter Island', countryLocation: 'Chile', timezone: 'Pacific/Easter' },
    { id: 119, city: 'Shanghai, China', cityName: 'Shanghai', countryLocation: 'China', timezone: 'Asia/Shanghai' },
    { id: 120, city: 'Urumqi, China', cityName: 'Urumqi', countryLocation: 'China', timezone: 'Asia/Urumqi' },
    { id: 121, city: 'Flying Fish Cove, Christmas Island', cityName: 'Flying Fish Cove', countryLocation: 'Christmas Island', timezone: 'Indian/Christmas' },
    { id: 122, city: 'West Island, Cocos (Keeling) Islands', cityName: 'West Island', countryLocation: 'Cocos (Keeling) Islands', timezone: 'Indian/Cocos' },
    { id: 123, city: 'Bogota, Colombia', cityName: 'Bogota', countryLocation: 'Colombia', timezone: 'America/Bogota' },
    { id: 124, city: 'Moroni, Comoros', cityName: 'Moroni', countryLocation: 'Comoros', timezone: 'Indian/Comoro' },
    { id: 125, city: 'Brazzaville, Congo', cityName: 'Brazzaville', countryLocation: 'Congo', timezone: 'Africa/Brazzaville' },
    { id: 126, city: 'Kinshasa, Democratic Republic of the Congo', cityName: 'Kinshasa', countryLocation: 'Democratic Republic of the Congo', timezone: 'Africa/Kinshasa' },
    { id: 127, city: 'Lubumbashi, Democratic Republic of the Congo', cityName: 'Lubumbashi', countryLocation: 'Democratic Republic of the Congo', timezone: 'Africa/Lubumbashi' },
    { id: 128, city: 'Rarotonga, Cook Islands', cityName: 'Rarotonga', countryLocation: 'Cook Islands', timezone: 'Pacific/Rarotonga' },
    { id: 129, city: 'San Jose, Costa Rica', cityName: 'San Jose', countryLocation: 'Costa Rica', timezone: 'America/Costa_Rica' },
    { id: 130, city: 'Zagreb, Croatia', cityName: 'Zagreb', countryLocation: 'Croatia', timezone: 'Europe/Zagreb' },
    { id: 131, city: 'Havana, Cuba', cityName: 'Havana', countryLocation: 'Cuba', timezone: 'America/Havana' },
    { id: 132, city: 'Willemstad, Curaçao', cityName: 'Willemstad', countryLocation: 'Curaçao', timezone: 'America/Curacao' },
    { id: 133, city: 'Famagusta, Cyprus', cityName: 'Famagusta', countryLocation: 'Cyprus', timezone: 'Asia/Famagusta' },
    { id: 134, city: 'Nicosia, Cyprus', cityName: 'Nicosia', countryLocation: 'Cyprus', timezone: 'Asia/Nicosia' },
    { id: 135, city: 'Prague, Czech Republic', cityName: 'Prague', countryLocation: 'Czech Republic', timezone: 'Europe/Prague' },
    { id: 136, city: 'Abidjan, Côte d\'Ivoire', cityName: 'Abidjan', countryLocation: 'Côte d\'Ivoire', timezone: 'Africa/Abidjan' },
    { id: 137, city: 'Copenhagen, Denmark', cityName: 'Copenhagen', countryLocation: 'Denmark', timezone: 'Europe/Copenhagen' },
    { id: 138, city: 'Djibouti', cityName: 'Djibouti', countryLocation: 'Djibouti', timezone: 'Africa/Djibouti' },
    { id: 139, city: 'Roseau, Dominica', cityName: 'Roseau', countryLocation: 'Dominica', timezone: 'America/Dominica' },
    { id: 140, city: 'Santo Domingo, Dominican Republic', cityName: 'Santo Domingo', countryLocation: 'Dominican Republic', timezone: 'America/Santo_Domingo' },
    { id: 141, city: 'Guayaquil, Ecuador', cityName: 'Guayaquil', countryLocation: 'Ecuador', timezone: 'America/Guayaquil' },
    { id: 142, city: 'Galapagos, Ecuador', cityName: 'Galapagos', countryLocation: 'Ecuador', timezone: 'Pacific/Galapagos' },
    { id: 143, city: 'Cairo, Egypt', cityName: 'Cairo', countryLocation: 'Egypt', timezone: 'Africa/Cairo' },
    { id: 144, city: 'San Salvador, El Salvador', cityName: 'San Salvador', countryLocation: 'El Salvador', timezone: 'America/El_Salvador' },
    { id: 145, city: 'Malabo, Equatorial Guinea', cityName: 'Malabo', countryLocation: 'Equatorial Guinea', timezone: 'Africa/Malabo' },
    { id: 146, city: 'Asmara, Eritrea', cityName: 'Asmara', countryLocation: 'Eritrea', timezone: 'Africa/Asmara' },
    { id: 147, city: 'Tallinn, Estonia', cityName: 'Tallinn', countryLocation: 'Estonia', timezone: 'Europe/Tallinn' },
    { id: 148, city: 'Addis Ababa, Ethiopia', cityName: 'Addis Ababa', countryLocation: 'Ethiopia', timezone: 'Africa/Addis_Ababa' },
    { id: 149, city: 'Stanley, Falkland Islands', cityName: 'Stanley', countryLocation: 'Falkland Islands', timezone: 'Atlantic/Stanley' },
    { id: 150, city: 'Torshavn, Faroe Islands', cityName: 'Torshavn', countryLocation: 'Faroe Islands', timezone: 'Atlantic/Faroe' },
    { id: 151, city: 'Suva, Fiji', cityName: 'Suva', countryLocation: 'Fiji', timezone: 'Pacific/Fiji' },
    { id: 152, city: 'Helsinki, Finland', cityName: 'Helsinki', countryLocation: 'Finland', timezone: 'Europe/Helsinki' },
    { id: 153, city: 'Paris, France', cityName: 'Paris', countryLocation: 'France', timezone: 'Europe/Paris' },
    { id: 154, city: 'Cayenne, French Guiana', cityName: 'Cayenne', countryLocation: 'French Guiana', timezone: 'America/Cayenne' },
    { id: 155, city: 'Gambier Islands, French Polynesia', cityName: 'Gambier Islands', countryLocation: 'French Polynesia', timezone: 'Pacific/Gambier' },
    { id: 156, city: 'Marquesas Islands, French Polynesia', cityName: 'Marquesas Islands', countryLocation: 'French Polynesia', timezone: 'Pacific/Marquesas' },
    { id: 157, city: 'Papeete, French Polynesia', cityName: 'Papeete', countryLocation: 'French Polynesia', timezone: 'Pacific/Tahiti' },
    { id: 158, city: 'Kerguelen Islands, French Southern Territories', cityName: 'Kerguelen Islands', countryLocation: 'French Southern Territories', timezone: 'Indian/Kerguelen' },
    { id: 159, city: 'Libreville, Gabon', cityName: 'Libreville', countryLocation: 'Gabon', timezone: 'Africa/Libreville' },
    { id: 160, city: 'Banjul, Gambia', cityName: 'Banjul', countryLocation: 'Gambia', timezone: 'Africa/Banjul' },
    { id: 161, city: 'Tbilisi, Georgia', cityName: 'Tbilisi', countryLocation: 'Georgia', timezone: 'Asia/Tbilisi' },
    { id: 162, city: 'Berlin, Germany', cityName: 'Berlin', countryLocation: 'Germany', timezone: 'Europe/Berlin' },
    { id: 163, city: 'Busingen, Germany', cityName: 'Busingen', countryLocation: 'Germany', timezone: 'Europe/Busingen' },
    { id: 164, city: 'Accra, Ghana', cityName: 'Accra', countryLocation: 'Ghana', timezone: 'Africa/Accra' },
    { id: 165, city: 'Gibraltar', cityName: 'Gibraltar', countryLocation: 'Gibraltar', timezone: 'Europe/Gibraltar' },
    { id: 166, city: 'Athens, Greece', cityName: 'Athens', countryLocation: 'Greece', timezone: 'Europe/Athens' },
    { id: 167, city: 'Danmarkshavn, Greenland', cityName: 'Danmarkshavn', countryLocation: 'Greenland', timezone: 'America/Danmarkshavn' },
    { id: 168, city: 'Nuuk, Greenland', cityName: 'Nuuk', countryLocation: 'Greenland', timezone: 'America/Nuuk' },
    { id: 169, city: 'Scoresbysund, Greenland', cityName: 'Scoresbysund', countryLocation: 'Greenland', timezone: 'America/Scoresbysund' },
    { id: 170, city: 'Thule, Greenland', cityName: 'Thule', countryLocation: 'Greenland', timezone: 'America/Thule' },
    { id: 171, city: 'St. George\'s, Grenada', cityName: 'St. George\'s', countryLocation: 'Grenada', timezone: 'America/Grenada' },
    { id: 172, city: 'Basse-Terre, Guadeloupe', cityName: 'Basse-Terre', countryLocation: 'Guadeloupe', timezone: 'America/Guadeloupe' },
    { id: 173, city: 'Hagåtña, Guam', cityName: 'Hagåtña', countryLocation: 'Guam', timezone: 'Pacific/Guam' },
    { id: 174, city: 'Guatemala City, Guatemala', cityName: 'Guatemala City', countryLocation: 'Guatemala', timezone: 'America/Guatemala' },
    { id: 175, city: 'St. Peter Port, Guernsey', cityName: 'St. Peter Port', countryLocation: 'Guernsey', timezone: 'Europe/Guernsey' },
    { id: 176, city: 'Conakry, Guinea', cityName: 'Conakry', countryLocation: 'Guinea', timezone: 'Africa/Conakry' },
    { id: 177, city: 'Bissau, Guinea-Bissau', cityName: 'Bissau', countryLocation: 'Guinea-Bissau', timezone: 'Africa/Bissau' },
    { id: 178, city: 'Georgetown, Guyana', cityName: 'Georgetown', countryLocation: 'Guyana', timezone: 'America/Guyana' },
    { id: 179, city: 'Port-au-Prince, Haiti', cityName: 'Port-au-Prince', countryLocation: 'Haiti', timezone: 'America/Port-au-Prince' },
    { id: 180, city: 'Vatican City', cityName: 'Vatican City', countryLocation: 'Vatican City', timezone: 'Europe/Vatican' },
    { id: 181, city: 'Tegucigalpa, Honduras', cityName: 'Tegucigalpa', countryLocation: 'Honduras', timezone: 'America/Tegucigalpa' },
    { id: 182, city: 'Hong Kong', cityName: 'Hong Kong', countryLocation: 'Hong Kong', timezone: 'Asia/Hong_Kong' },
    { id: 183, city: 'Budapest, Hungary', cityName: 'Budapest', countryLocation: 'Hungary', timezone: 'Europe/Budapest' },
    { id: 184, city: 'Reykjavik, Iceland', cityName: 'Reykjavik', countryLocation: 'Iceland', timezone: 'Atlantic/Reykjavik' },
    { id: 185, city: 'New Delhi, India', cityName: 'New Delhi', countryLocation: 'India', timezone: 'Asia/Kolkata' },
    { id: 186, city: 'Jakarta, Indonesia', cityName: 'Jakarta', countryLocation: 'Indonesia', timezone: 'Asia/Jakarta' },
    { id: 187, city: 'Jayapura, Indonesia', cityName: 'Jayapura', countryLocation: 'Indonesia', timezone: 'Asia/Jayapura' },
    { id: 188, city: 'Makassar, Indonesia', cityName: 'Makassar', countryLocation: 'Indonesia', timezone: 'Asia/Makassar' },
    { id: 189, city: 'Pontianak, Indonesia', cityName: 'Pontianak', countryLocation: 'Indonesia', timezone: 'Asia/Pontianak' },
    { id: 190, city: 'Tehran, Iran', cityName: 'Tehran', countryLocation: 'Iran', timezone: 'Asia/Tehran' },
    { id: 191, city: 'Baghdad, Iraq', cityName: 'Baghdad', countryLocation: 'Iraq', timezone: 'Asia/Baghdad' },
    { id: 192, city: 'Dublin, Ireland', cityName: 'Dublin', countryLocation: 'Ireland', timezone: 'Europe/Dublin' },
    { id: 193, city: 'Douglas, Isle of Man', cityName: 'Douglas', countryLocation: 'Isle of Man', timezone: 'Europe/Isle_of_Man' },
    { id: 194, city: 'Jerusalem, Israel', cityName: 'Jerusalem', countryLocation: 'Israel', timezone: 'Asia/Jerusalem' },
    { id: 195, city: 'Rome, Italy', cityName: 'Rome', countryLocation: 'Italy', timezone: 'Europe/Rome' },
    { id: 196, city: 'Kingston, Jamaica', cityName: 'Kingston', countryLocation: 'Jamaica', timezone: 'America/Jamaica' },
    { id: 197, city: 'Tokyo, Japan', cityName: 'Tokyo', countryLocation: 'Japan', timezone: 'Asia/Tokyo' },
    { id: 198, city: 'St. Helier, Jersey', cityName: 'St. Helier', countryLocation: 'Jersey', timezone: 'Europe/Jersey' },
    { id: 199, city: 'Amman, Jordan', cityName: 'Amman', countryLocation: 'Jordan', timezone: 'Asia/Amman' },
    { id: 200, city: 'Almaty, Kazakhstan', cityName: 'Almaty', countryLocation: 'Kazakhstan', timezone: 'Asia/Almaty' },
    { id: 201, city: 'Aqtau, Kazakhstan', cityName: 'Aqtau', countryLocation: 'Kazakhstan', timezone: 'Asia/Aqtau' },
    { id: 202, city: 'Aqtobe, Kazakhstan', cityName: 'Aqtobe', countryLocation: 'Kazakhstan', timezone: 'Asia/Aqtobe' },
    { id: 203, city: 'Atyrau, Kazakhstan', cityName: 'Atyrau', countryLocation: 'Kazakhstan', timezone: 'Asia/Atyrau' },
    { id: 204, city: 'Oral, Kazakhstan', cityName: 'Oral', countryLocation: 'Kazakhstan', timezone: 'Asia/Oral' },
    { id: 205, city: 'Qostanay, Kazakhstan', cityName: 'Qostanay', countryLocation: 'Kazakhstan', timezone: 'Asia/Qostanay' },
    { id: 206, city: 'Qyzylorda, Kazakhstan', cityName: 'Qyzylorda', countryLocation: 'Kazakhstan', timezone: 'Asia/Qyzylorda' },
    { id: 207, city: 'Nairobi, Kenya', cityName: 'Nairobi', countryLocation: 'Kenya', timezone: 'Africa/Nairobi' },
    { id: 208, city: 'Tarawa, Kiribati', cityName: 'Tarawa', countryLocation: 'Kiribati', timezone: 'Pacific/Tarawa' },
    { id: 209, city: 'Kiritimati, Kiribati', cityName: 'Kiritimati', countryLocation: 'Kiribati', timezone: 'Pacific/Kiritimati' },
    { id: 210, city: 'Pyongyang, North Korea', cityName: 'Pyongyang', countryLocation: 'North Korea', timezone: 'Asia/Pyongyang' },
    { id: 211, city: 'Seoul, South Korea', cityName: 'Seoul', countryLocation: 'South Korea', timezone: 'Asia/Seoul' },
    { id: 212, city: 'Kuwait City, Kuwait', cityName: 'Kuwait City', countryLocation: 'Kuwait', timezone: 'Asia/Kuwait' },
    { id: 213, city: 'Bishkek, Kyrgyzstan', cityName: 'Bishkek', countryLocation: 'Kyrgyzstan', timezone: 'Asia/Bishkek' },
    { id: 214, city: 'Vientiane, Laos', cityName: 'Vientiane', countryLocation: 'Laos', timezone: 'Asia/Vientiane' },
    { id: 215, city: 'Riga, Latvia', cityName: 'Riga', countryLocation: 'Latvia', timezone: 'Europe/Riga' },
    { id: 216, city: 'Beirut, Lebanon', cityName: 'Beirut', countryLocation: 'Lebanon', timezone: 'Asia/Beirut' },
    { id: 217, city: 'Maseru, Lesotho', cityName: 'Maseru', countryLocation: 'Lesotho', timezone: 'Africa/Maseru' },
    { id: 218, city: 'Monrovia, Liberia', cityName: 'Monrovia', countryLocation: 'Liberia', timezone: 'Africa/Monrovia' },
    { id: 219, city: 'Tripoli, Libya', cityName: 'Tripoli', countryLocation: 'Libya', timezone: 'Africa/Tripoli' },
    { id: 220, city: 'Vaduz, Liechtenstein', cityName: 'Vaduz', countryLocation: 'Liechtenstein', timezone: 'Europe/Vaduz' },
    { id: 221, city: 'Vilnius, Lithuania', cityName: 'Vilnius', countryLocation: 'Lithuania', timezone: 'Europe/Vilnius' },
    { id: 222, city: 'Luxembourg City, Luxembourg', cityName: 'Luxembourg City', countryLocation: 'Luxembourg', timezone: 'Europe/Luxembourg' },
    { id: 223, city: 'Macau, China', cityName: 'Macau', countryLocation: 'China', timezone: 'Asia/Macau' },
    { id: 224, city: 'Skopje, North Macedonia', cityName: 'Skopje', countryLocation: 'North Macedonia', timezone: 'Europe/Skopje' },
    { id: 225, city: 'Antananarivo, Madagascar', cityName: 'Antananarivo', countryLocation: 'Madagascar', timezone: 'Indian/Antananarivo' },
    { id: 226, city: 'Lilongwe, Malawi', cityName: 'Lilongwe', countryLocation: 'Malawi', timezone: 'Africa/Blantyre' },
    { id: 227, city: 'Kuala Lumpur, Malaysia', cityName: 'Kuala Lumpur', countryLocation: 'Malaysia', timezone: 'Asia/Kuala_Lumpur' },
    { id: 228, city: 'Kuching, Malaysia', cityName: 'Kuching', countryLocation: 'Malaysia', timezone: 'Asia/Kuching' },
    { id: 229, city: 'Male, Maldives', cityName: 'Male', countryLocation: 'Maldives', timezone: 'Indian/Maldives' },
    { id: 230, city: 'Bamako, Mali', cityName: 'Bamako', countryLocation: 'Mali', timezone: 'Africa/Bamako' },
    { id: 231, city: 'Valletta, Malta', cityName: 'Valletta', countryLocation: 'Malta', timezone: 'Europe/Malta' },
    { id: 232, city: 'Majuro, Marshall Islands', cityName: 'Majuro', countryLocation: 'Marshall Islands', timezone: 'Pacific/Majuro' },
    { id: 233, city: 'Fort-de-France, Martinique', cityName: 'Fort-de-France', countryLocation: 'Martinique', timezone: 'America/Martinique' },
    { id: 234, city: 'Nouakchott, Mauritania', cityName: 'Nouakchott', countryLocation: 'Mauritania', timezone: 'Africa/Nouakchott' },
    { id: 235, city: 'Port Louis, Mauritius', cityName: 'Port Louis', countryLocation: 'Mauritius', timezone: 'Indian/Mauritius' },
    { id: 236, city: 'Mamoudzou, Mayotte', cityName: 'Mamoudzou', countryLocation: 'Mayotte', timezone: 'Indian/Mayotte' },
    { id: 237, city: 'Mexico City, Mexico', cityName: 'Mexico City', countryLocation: 'Mexico', timezone: 'America/Mexico_City' },
    { id: 238, city: 'Palikir, Micronesia', cityName: 'Palikir', countryLocation: 'Micronesia', timezone: 'Pacific/Pohnpei' },
    { id: 239, city: 'Chisinau, Moldova', cityName: 'Chisinau', countryLocation: 'Moldova', timezone: 'Europe/Chisinau' },
    { id: 240, city: 'Monaco', cityName: 'Monaco', countryLocation: 'Monaco', timezone: 'Europe/Monaco' },
    { id: 241, city: 'Ulaanbaatar, Mongolia', cityName: 'Ulaanbaatar', countryLocation: 'Mongolia', timezone: 'Asia/Ulaanbaatar' },
    { id: 242, city: 'Podgorica, Montenegro', cityName: 'Podgorica', countryLocation: 'Montenegro', timezone: 'Europe/Podgorica' },
    { id: 243, city: 'Plymouth, Montserrat', cityName: 'Plymouth', countryLocation: 'Montserrat', timezone: 'America/Montserrat' },
    { id: 244, city: 'Casablanca, Morocco', cityName: 'Casablanca', countryLocation: 'Morocco', timezone: 'Africa/Casablanca' },
    { id: 245, city: 'Maputo, Mozambique', cityName: 'Maputo', countryLocation: 'Mozambique', timezone: 'Africa/Maputo' },
    { id: 246, city: 'Yangon, Myanmar', cityName: 'Yangon', countryLocation: 'Myanmar', timezone: 'Asia/Yangon' },
    { id: 247, city: 'Windhoek, Namibia', cityName: 'Windhoek', countryLocation: 'Namibia', timezone: 'Africa/Windhoek' },
    { id: 248, city: 'Yaren, Nauru', cityName: 'Yaren', countryLocation: 'Nauru', timezone: 'Pacific/Nauru' },
    { id: 249, city: 'Kathmandu, Nepal', cityName: 'Kathmandu', countryLocation: 'Nepal', timezone: 'Asia/Kathmandu' },
    { id: 250, city: 'Amsterdam, Netherlands', cityName: 'Amsterdam', countryLocation: 'Netherlands', timezone: 'Europe/Amsterdam' },
    { id: 251, city: 'Noumea, New Caledonia', cityName: 'Noumea', countryLocation: 'New Caledonia', timezone: 'Pacific/Noumea' },
    { id: 252, city: 'Wellington, New Zealand', cityName: 'Wellington', countryLocation: 'New Zealand', timezone: 'Pacific/Auckland' },
    { id: 253, city: 'Managua, Nicaragua', cityName: 'Managua', countryLocation: 'Nicaragua', timezone: 'America/Managua' },
    { id: 254, city: 'Niamey, Niger', cityName: 'Niamey', countryLocation: 'Niger', timezone: 'Africa/Niamey' },
    { id: 255, city: 'Lagos, Nigeria', cityName: 'Lagos', countryLocation: 'Nigeria', timezone: 'Africa/Lagos' },
    { id: 256, city: 'Alofi, Niue', cityName: 'Alofi', countryLocation: 'Niue', timezone: 'Pacific/Niue' },
    { id: 257, city: 'Kingston, Norfolk Island', cityName: 'Kingston', countryLocation: 'Norfolk Island', timezone: 'Pacific/Norfolk' },
    { id: 258, city: 'Saipan, Northern Mariana Islands', cityName: 'Saipan', countryLocation: 'Northern Mariana Islands', timezone: 'Pacific/Saipan' },
    { id: 259, city: 'Oslo, Norway', cityName: 'Oslo', countryLocation: 'Norway', timezone: 'Europe/Oslo' },
    { id: 260, city: 'Muscat, Oman', cityName: 'Muscat', countryLocation: 'Oman', timezone: 'Asia/Muscat' },
    { id: 261, city: 'Karachi, Pakistan', cityName: 'Karachi', countryLocation: 'Pakistan', timezone: 'Asia/Karachi' },
    { id: 262, city: 'Ngerulmud, Palau', cityName: 'Ngerulmud', countryLocation: 'Palau', timezone: 'Pacific/Palau' },
    { id: 263, city: 'Gaza, Palestine', cityName: 'Gaza', countryLocation: 'Palestine', timezone: 'Asia/Gaza' },
    { id: 264, city: 'Panama City, Panama', cityName: 'Panama City', countryLocation: 'Panama', timezone: 'America/Panama' },
    { id: 265, city: 'Port Moresby, Papua New Guinea', cityName: 'Port Moresby', countryLocation: 'Papua New Guinea', timezone: 'Pacific/Port_Moresby' },
    { id: 266, city: 'Asunción, Paraguay', cityName: 'Asunción', countryLocation: 'Paraguay', timezone: 'America/Asuncion' },
    { id: 267, city: 'Lima, Peru', cityName: 'Lima', countryLocation: 'Peru', timezone: 'America/Lima' },
    { id: 268, city: 'Manila, Philippines', cityName: 'Manila', countryLocation: 'Philippines', timezone: 'Asia/Manila' },
    { id: 269, city: 'Adamstown, Pitcairn', cityName: 'Adamstown', countryLocation: 'Pitcairn', timezone: 'Pacific/Pitcairn' },
    { id: 270, city: 'Warsaw, Poland', cityName: 'Warsaw', countryLocation: 'Poland', timezone: 'Europe/Warsaw' },
    { id: 271, city: 'Lisbon, Portugal', cityName: 'Lisbon', countryLocation: 'Portugal', timezone: 'Europe/Lisbon' },
    { id: 272, city: 'San Juan, Puerto Rico', cityName: 'San Juan', countryLocation: 'Puerto Rico', timezone: 'America/Puerto_Rico' },
    { id: 273, city: 'Doha, Qatar', cityName: 'Doha', countryLocation: 'Qatar', timezone: 'Asia/Qatar' },
    { id: 274, city: 'Bucharest, Romania', cityName: 'Bucharest', countryLocation: 'Romania', timezone: 'Europe/Bucharest' },
    { id: 275, city: 'Moscow, Russia', cityName: 'Moscow', countryLocation: 'Russia', timezone: 'Europe/Moscow' },
    { id: 276, city: 'Kigali, Rwanda', cityName: 'Kigali', countryLocation: 'Rwanda', timezone: 'Africa/Kigali' },
    { id: 277, city: 'Saint-Denis, Réunion', cityName: 'Saint-Denis', countryLocation: 'Réunion', timezone: 'Indian/Reunion' },
    { id: 278, city: 'Gustavia, Saint Barthélemy', cityName: 'Gustavia', countryLocation: 'Saint Barthélemy', timezone: 'America/St_Barthelemy' },
    { id: 279, city: 'Jamestown, Saint Helena', cityName: 'Jamestown', countryLocation: 'Saint Helena', timezone: 'Atlantic/St_Helena' },
    { id: 280, city: 'Basseterre, Saint Kitts and Nevis', cityName: 'Basseterre', countryLocation: 'Saint Kitts and Nevis', timezone: 'America/St_Kitts' },
    { id: 281, city: 'Castries, Saint Lucia', cityName: 'Castries', countryLocation: 'Saint Lucia', timezone: 'America/St_Lucia' },
    { id: 282, city: 'Marigot, Saint Martin', cityName: 'Marigot', countryLocation: 'Saint Martin', timezone: 'America/Marigot' },
    { id: 283, city: 'Saint-Pierre, Saint Pierre and Miquelon', cityName: 'Saint-Pierre', countryLocation: 'Saint Pierre and Miquelon', timezone: 'America/Miquelon' },
    { id: 284, city: 'Kingstown, Saint Vincent and the Grenadines', cityName: 'Kingstown', countryLocation: 'Saint Vincent and the Grenadines', timezone: 'America/St_Vincent' },
    { id: 285, city: 'Apia, Samoa', cityName: 'Apia', countryLocation: 'Samoa', timezone: 'Pacific/Apia' },
    { id: 286, city: 'San Marino', cityName: 'San Marino', countryLocation: 'San Marino', timezone: 'Europe/San_Marino' },
    { id: 287, city: 'São Tomé, Sao Tome and Principe', cityName: 'São Tomé', countryLocation: 'Sao Tome and Principe', timezone: 'Africa/Sao_Tome' },
    { id: 288, city: 'Riyadh, Saudi Arabia', cityName: 'Riyadh', countryLocation: 'Saudi Arabia', timezone: 'Asia/Riyadh' },
    { id: 289, city: 'Dakar, Senegal', cityName: 'Dakar', countryLocation: 'Senegal', timezone: 'Africa/Dakar' },
    { id: 290, city: 'Belgrade, Serbia', cityName: 'Belgrade', countryLocation: 'Serbia', timezone: 'Europe/Belgrade' },
    { id: 291, city: 'Victoria, Seychelles', cityName: 'Victoria', countryLocation: 'Seychelles', timezone: 'Indian/Mahe' },
    { id: 292, city: 'Freetown, Sierra Leone', cityName: 'Freetown', countryLocation: 'Sierra Leone', timezone: 'Africa/Freetown' },
    { id: 293, city: 'Singapore', cityName: 'Singapore', countryLocation: 'Singapore', timezone: 'Asia/Singapore' },
    { id: 294, city: 'Philipsburg, Sint Maarten', cityName: 'Philipsburg', countryLocation: 'Sint Maarten', timezone: 'America/Lower_Princes' },
    { id: 295, city: 'Bratislava, Slovakia', cityName: 'Bratislava', countryLocation: 'Slovakia', timezone: 'Europe/Bratislava' },
    { id: 296, city: 'Ljubljana, Slovenia', cityName: 'Ljubljana', countryLocation: 'Slovenia', timezone: 'Europe/Ljubljana' },
    { id: 297, city: 'Honiara, Solomon Islands', cityName: 'Honiara', countryLocation: 'Solomon Islands', timezone: 'Pacific/Guadalcanal' },
    { id: 298, city: 'Mogadishu, Somalia', cityName: 'Mogadishu', countryLocation: 'Somalia', timezone: 'Africa/Mogadishu' },
    { id: 299, city: 'Pretoria, South Africa', cityName: 'Pretoria', countryLocation: 'South Africa', timezone: 'Africa/Johannesburg' },
    { id: 300, city: 'King Edward Point, South Georgia and the South Sandwich Islands', cityName: 'King Edward Point', countryLocation: 'South Georgia and the South Sandwich Islands', timezone: 'Atlantic/South_Georgia' },
    { id: 301, city: 'Juba, South Sudan', cityName: 'Juba', countryLocation: 'South Sudan', timezone: 'Africa/Juba' },
    { id: 302, city: 'Madrid, Spain', cityName: 'Madrid', countryLocation: 'Spain', timezone: 'Europe/Madrid' },
    { id: 303, city: 'Colombo, Sri Lanka', cityName: 'Colombo', countryLocation: 'Sri Lanka', timezone: 'Asia/Colombo' },
    { id: 304, city: 'Khartoum, Sudan', cityName: 'Khartoum', countryLocation: 'Sudan', timezone: 'Africa/Khartoum' },
    { id: 305, city: 'Paramaribo, Suriname', cityName: 'Paramaribo', countryLocation: 'Suriname', timezone: 'America/Paramaribo' },
    { id: 306, city: 'Longyearbyen, Svalbard and Jan Mayen', cityName: 'Longyearbyen', countryLocation: 'Svalbard and Jan Mayen', timezone: 'Arctic/Longyearbyen' },
    { id: 307, city: 'Stockholm, Sweden', cityName: 'Stockholm', countryLocation: 'Sweden', timezone: 'Europe/Stockholm' },
    { id: 308, city: 'Zurich, Switzerland', cityName: 'Zurich', countryLocation: 'Switzerland', timezone: 'Europe/Zurich' },
    { id: 309, city: 'Damascus, Syria', cityName: 'Damascus', countryLocation: 'Syria', timezone: 'Asia/Damascus' },
    { id: 310, city: 'Taipei, Taiwan', cityName: 'Taipei', countryLocation: 'Taiwan', timezone: 'Asia/Taipei' },
    { id: 311, city: 'Dushanbe, Tajikistan', cityName: 'Dushanbe', countryLocation: 'Tajikistan', timezone: 'Asia/Dushanbe' },
    { id: 312, city: 'Dar es Salaam, Tanzania', cityName: 'Dar es Salaam', countryLocation: 'Tanzania', timezone: 'Africa/Dar_es_Salaam' },
    { id: 313, city: 'Bangkok, Thailand', cityName: 'Bangkok', countryLocation: 'Thailand', timezone: 'Asia/Bangkok' },
    { id: 314, city: 'Dili, Timor-Leste', cityName: 'Dili', countryLocation: 'Timor-Leste', timezone: 'Asia/Dili' },
    { id: 315, city: 'Lome, Togo', cityName: 'Lome', countryLocation: 'Togo', timezone: 'Africa/Lome' },
    { id: 316, city: 'Fakaofo, Tokelau', cityName: 'Fakaofo', countryLocation: 'Tokelau', timezone: 'Pacific/Fakaofo' },
    { id: 317, city: 'Nuku\'alofa, Tonga', cityName: 'Nuku\'alofa', countryLocation: 'Tonga', timezone: 'Pacific/Tongatapu' },
    { id: 318, city: 'Port of Spain, Trinidad and Tobago', cityName: 'Port of Spain', countryLocation: 'Trinidad and Tobago', timezone: 'America/Port_of_Spain' },
    { id: 319, city: 'Tunis, Tunisia', cityName: 'Tunis', countryLocation: 'Tunisia', timezone: 'Africa/Tunis' },
    { id: 320, city: 'Istanbul, Turkey', cityName: 'Istanbul', countryLocation: 'Turkey', timezone: 'Europe/Istanbul' },
    { id: 321, city: 'Ashgabat, Turkmenistan', cityName: 'Ashgabat', countryLocation: 'Turkmenistan', timezone: 'Asia/Ashgabat' },
    { id: 322, city: 'Cockburn Town, Turks and Caicos Islands', cityName: 'Cockburn Town', countryLocation: 'Turks and Caicos Islands', timezone: 'America/Grand_Turk' },
    { id: 323, city: 'Funafuti, Tuvalu', cityName: 'Funafuti', countryLocation: 'Tuvalu', timezone: 'Pacific/Funafuti' },
    { id: 324, city: 'Kampala, Uganda', cityName: 'Kampala', countryLocation: 'Uganda', timezone: 'Africa/Kampala' },
    { id: 325, city: 'Kyiv, Ukraine', cityName: 'Kyiv', countryLocation: 'Ukraine', timezone: 'Europe/Kiev' },
    { id: 326, city: 'Abu Dhabi, United Arab Emirates', cityName: 'Abu Dhabi', countryLocation: 'United Arab Emirates', timezone: 'Asia/Dubai' },
    { id: 327, city: 'London, United Kingdom', cityName: 'London', countryLocation: 'United Kingdom', timezone: 'Europe/London' },
    { id: 328, city: 'New York, United States', cityName: 'New York', countryLocation: 'United States', timezone: 'America/New_York' },
    { id: 329, city: 'Montevideo, Uruguay', cityName: 'Montevideo', countryLocation: 'Uruguay', timezone: 'America/Montevideo' },
    { id: 330, city: 'Tashkent, Uzbekistan', cityName: 'Tashkent', countryLocation: 'Uzbekistan', timezone: 'Asia/Tashkent' },
    { id: 331, city: 'Port Vila, Vanuatu', cityName: 'Port Vila', countryLocation: 'Vanuatu', timezone: 'Pacific/Efate' },
    { id: 332, city: 'Caracas, Venezuela', cityName: 'Caracas', countryLocation: 'Venezuela', timezone: 'America/Caracas' },
    { id: 333, city: 'Hanoi, Vietnam', cityName: 'Hanoi', countryLocation: 'Vietnam', timezone: 'Asia/Ho_Chi_Minh' },
    { id: 334, city: 'Road Town, British Virgin Islands', cityName: 'Road Town', countryLocation: 'British Virgin Islands', timezone: 'America/Tortola' },
    { id: 335, city: 'Charlotte Amalie, U.S. Virgin Islands', cityName: 'Charlotte Amalie', countryLocation: 'U.S. Virgin Islands', timezone: 'America/St_Thomas' },
    { id: 336, city: 'Mata-Utu, Wallis and Futuna', cityName: 'Mata-Utu', countryLocation: 'Wallis and Futuna', timezone: 'Pacific/Wallis' },
    { id: 337, city: 'El Aaiún, Western Sahara', cityName: 'El Aaiún', countryLocation: 'Western Sahara', timezone: 'Africa/El_Aaiun' },
    { id: 338, city: 'Sana\'a, Yemen', cityName: 'Sana\'a', countryLocation: 'Yemen', timezone: 'Asia/Aden' },
    { id: 339, city: 'Lusaka, Zambia', cityName: 'Lusaka', countryLocation: 'Zambia', timezone: 'Africa/Lusaka' },
    { id: 340, city: 'Harare, Zimbabwe', cityName: 'Harare', countryLocation: 'Zimbabwe', timezone: 'Africa/Harare' },
    { id: 341, city: 'Mariehamn, Åland Islands', cityName: 'Mariehamn', countryLocation: 'Åland Islands', timezone: 'Europe/Mariehamn' },
    { id: 342, city: 'Honolulu, United States', cityName: 'Honolulu', countryLocation: 'United States', timezone: 'Pacific/Honolulu' },
    { id: 343, city: 'Anchorage, United States', cityName: 'Anchorage', countryLocation: 'United States', timezone: 'America/Anchorage' },
    { id: 344, city: 'Los Angeles, United States', cityName: 'Los Angeles', countryLocation: 'United States', timezone: 'America/Los_Angeles' }
  ];
  